# .pre-commit-config.yaml
# Professional Code Quality Enforcement Protocol
# This configuration ensures all code meets industry standards before commit

repos:
  # Basic file and formatting checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        description: Check YAML files for syntax errors
      - id: end-of-file-fixer
        description: Ensure files end with a newline
      - id: trailing-whitespace
        description: Remove trailing whitespace
      - id: check-added-large-files
        description: Prevent large files from being committed
      - id: check-merge-conflict
        description: Check for merge conflict strings
      - id: check-json
        description: Check JSON files for syntax errors
      - id: check-toml
        description: Check TOML files for syntax errors
      - id: check-ast
        description: Check Python files for valid syntax

  # Black: The uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        description: Format Python code with Black
        language_version: python3

  # Ruff: An extremely fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        description: Run Ruff linter with auto-fixes
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        description: Format Python code with Ruff

  # MyPy: Static type checker for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        description: Run MyPy static type checking
        args: [--strict, --ignore-missing-imports]
        additional_dependencies: [
          types-requests,
          types-PyYAML,
          types-setuptools,
          types-toml
        ]
