# M1 MacBook Air Optimized Docker Compose
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "8080:8080"
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - OMP_NUM_THREADS=8
      - MKL_NUM_THREADS=8
    volumes:
      - .:/app
    restart: unless-stopped

  # Optional: Add Redis for caching (ARM64 optimized)
  redis:
    image: redis:7-alpine
    platform: linux/arm64
    ports:
      - "6379:6379"
    restart: unless-stopped
