CREATE TABLE IF NOT EXISTS income_streams (id INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL, title TEXT, config JSON, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS affiliate_links (id INTEGER PRIMARY KEY AUTOINCREMENT, program TEXT, url TEXT, notes TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS digital_products (id INTEGER PRIMARY KEY AUTOINCREMENT, sku TEXT, name TEXT, price_cents INTEGER DEFAULT 0, payload_path TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS courses (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, syllabus JSON, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS webinars (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, schedule DATETIME, notes TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
