# Kubernetes health probe configuration
# Add these to your deployment spec under containers:

livenessProbe:
  httpGet:
    path: /health/live
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health/ready
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Example deployment snippet:
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: online-production-api
# spec:
#   template:
#     spec:
#       containers:
#       - name: api
#         image: your-image:tag
#         ports:
#         - containerPort: 8000
#         livenessProbe:
#           httpGet:
#             path: /health/live
#             port: 8000
#           initialDelaySeconds: 10
#           periodSeconds: 10
#         readinessProbe:
#           httpGet:
#             path: /health/ready
#             port: 8000
#           initialDelaySeconds: 5
#           periodSeconds: 5
