[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_optional = true
strict_optional = true
disallow_untyped_defs = false

[tool.coverage.run]
branch = true
source = ["."]
omit = [
  "venv*/**",
  "site-packages/**"
]
