line-length = 100
target-version = "py311"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false

[lint]
select = ["E","F","W","I","B","UP","SIM","S","C90"]
ignore = [
  "E203"
]
