title = "Gitleaks config"

[allowlist]
description = "Allowed false positives"
regexes = [
  '''(?i)example_key|dummy|notreal'''
]

[[rules]]
id = "generic-credential"
description = "Generic credential pattern"
regex = '''(?i)(apikey|api_key|secret|passwd|password|token)\s*[:=]\s*[A-Za-z0-9_\-]{12,}'''
secretGroup = 0
entropy = 3.5
keywords = ["key","secret","token","passwd","password"]
