name: LIVE Production Deployment - NO VIRTUAL ENVIRONMENTS

# LIVE deployment workflow - NO VIRTUAL ENVIRONMENTS
# Production-only deployment with strict authorization requirements

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment - PRODUCTION ONLY"
        required: true
        default: "production"
        type: choice
        options:
          - production
      automation_authorized:
        description: "Automation explicitly authorized by user"
        required: true
        default: false
        type: boolean
      skip_tests:
        description: "Skip tests (NEVER recommended for live production)"
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: "18"
  PYTHON_VERSION: "3.11"

jobs:
  # Phase 1: LIVE Production Validation - NO VIRTUAL ENVIRONMENTS
  validate:
    name: "Validate LIVE Production Configuration"
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    outputs:
      environment: ${{ steps.validate.outputs.environment }}
      deploy_url: ${{ steps.validate.outputs.deploy_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Enforce LIVE deployment rules
        id: validate
        run: |
          echo "🚨 LIVE PRODUCTION DEPLOYMENT - NO VIRTUAL ENVIRONMENTS"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Automation authorized: ${{ github.event.inputs.automation_authorized }}"
          echo "Skip tests: ${{ github.event.inputs.skip_tests }}"
          
          # Enforce production-only deployment
          if [[ "${{ github.event.inputs.environment }}" != "production" ]]; then
            echo "❌ ERROR: Only production deployments allowed. No virtual environments."
            exit 1
          fi
          
          # Require explicit automation authorization
          if [[ "${{ github.event.inputs.automation_authorized }}" != "true" ]]; then
            echo "❌ ERROR: Automation not authorized. User must explicitly authorize deployment."
            echo "Please check 'Automation explicitly authorized by user' to proceed."
            exit 1
          fi
          
          echo "🚨 PRODUCTION DEPLOYMENT DETECTED"
          echo "environment=production" >> $GITHUB_OUTPUT
          echo "deploy_url=https://your-production-site.netlify.app" >> $GITHUB_OUTPUT
          
          # Production safety checks
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "❌ Production deployments must be from main branch"
            exit 1
          fi
          
          if [[ "${{ github.event.inputs.skip_tests }}" == "true" ]]; then
            echo "❌ Cannot skip tests for production deployment"
            exit 1
          fi
          
          echo "✅ LIVE PRODUCTION DEPLOYMENT AUTHORIZED"
      
      - name: Check required secrets
        run: |
          echo "🔐 Checking deployment secrets..."
          
          # Netlify secrets
          if [[ -z "${{ secrets.NETLIFY_AUTH_TOKEN }}" ]]; then
            echo "❌ NETLIFY_AUTH_TOKEN required"
            exit 1
          fi
          
          if [[ -z "${{ secrets.NETLIFY_SITE_ID }}" ]]; then
            echo "❌ NETLIFY_SITE_ID required"
            exit 1
          fi
          
          # Production-specific secrets
          if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            if [[ -z "${{ secrets.SECRET_KEY }}" ]]; then
              echo "❌ SECRET_KEY required for production"
              exit 1
            fi
          fi
          
          echo "✅ Required secrets configured"

  # Phase 2: Code Quality and Security Scanning
  security_scan:
    name: "Security & Quality Checks"
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety flake8
      
      - name: Python security scan
        run: |
          echo "🔍 Running Python security scan..."
          bandit -r . -f json -o bandit-report.json || true
          safety check --json --output safety-report.json || true
          echo "✅ Security scan completed"
      
      - name: Code quality check
        run: |
          echo "📋 Running code quality checks..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          echo "✅ Code quality check passed"
      
      - name: Secret scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified

  # Phase 3: Testing
  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    needs: [validate, security_scan]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.skip_tests != 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx
      
      - name: Test configuration validation
        run: |
          echo "🧪 Testing configuration validation..."
          python -c "
          import sys
          sys.path.append('.')
          try:
              from config.validator import validate_startup_config
              print('✅ Configuration validator working')
          except ImportError as e:
              print(f'❌ Configuration validator failed: {e}')
              sys.exit(1)
          "
      
      - name: Run Python tests
        run: |
          echo "🧪 Running Python tests..."
          python -m pytest tests/ -v --tb=short || echo "No tests found"

  # Existing preview deployment for PRs
  deploy-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE_STAGING }}

      - name: Deploy to Netlify (Preview)
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./frontend/dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Preview: ${{ github.event.pull_request.title }}"
          alias: deploy-preview-${{ github.event.number }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  # Phase 4: Production Deployment
  deploy-production:
    name: "Deploy to ${{ needs.validate.outputs.environment }}"
    runs-on: ubuntu-latest
    needs: [validate, security_scan, test]
    if: github.event_name == 'workflow_dispatch' && (success() || github.event.inputs.skip_tests == 'true')
    environment:
      name: ${{ needs.validate.outputs.environment }}
      url: ${{ needs.validate.outputs.deploy_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build application
        env:
          NODE_ENV: production
          VITE_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          # Pet Care APIs (optional)
          VITE_EBIRD_API_TOKEN: ${{ secrets.EBIRD_API_TOKEN }}
          VITE_DOG_API_KEY: ${{ secrets.DOG_API_KEY }}
          VITE_CAT_API_KEY: ${{ secrets.CAT_API_KEY }}
          VITE_PETFINDER_KEY: ${{ secrets.PETFINDER_KEY }}
          # Tele-vet APIs (optional)
          VITE_VETSTER_API_KEY: ${{ secrets.VETSTER_API_KEY }}
          VITE_PAWP_API_KEY: ${{ secrets.PAWP_API_KEY }}
          VITE_AIRVET_API_KEY: ${{ secrets.AIRVET_API_KEY }}
          VITE_CALENDLY_TOKEN: ${{ secrets.CALENDLY_TOKEN }}
        run: |
          echo "🏗️ Building application for ${{ needs.validate.outputs.environment }}..."
          cd frontend
          npm run build
          echo "✅ Build completed"
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./frontend/dist"
          production-deploy: ${{ needs.validate.outputs.environment == 'production' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "🚀 ${{ needs.validate.outputs.environment }} deployment from ${{ github.sha }}"
          alias: ${{ needs.validate.outputs.environment == 'staging' && 'staging' || '' }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Post-deployment verification
        run: |
          echo "🔍 Verifying deployment..."
          
          # Wait for deployment to be ready
          sleep 30
          
          # Basic health check
          DEPLOY_URL="${{ needs.validate.outputs.deploy_url }}"
          echo "Testing deployment at: $DEPLOY_URL"
          
          # Check if site is accessible
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$DEPLOY_URL" || echo "000")
          
          if [[ "$HTTP_STATUS" == "200" ]]; then
            echo "✅ Deployment verification successful"
            echo "🌐 Site is live at: $DEPLOY_URL"
          else
            echo "❌ Deployment verification failed (HTTP $HTTP_STATUS)"
            echo "🔧 Please check the deployment logs"
            exit 1
          fi
      
      - name: Notify deployment success
        if: success()
        run: |
          echo "🎉 Deployment to ${{ needs.validate.outputs.environment }} completed successfully!"
          echo "📍 URL: ${{ needs.validate.outputs.deploy_url }}"
          echo "🔧 Environment: ${{ needs.validate.outputs.environment }}"
          echo "📝 Commit: ${{ github.sha }}"
          
          if [[ "${{ needs.validate.outputs.environment }}" == "production" ]]; then
            echo "🚨 PRODUCTION DEPLOYMENT COMPLETE"
            echo "🔍 Monitor application performance and error rates"
            echo "📊 Check analytics and user feedback"
          fi
